spring:
  datasource:
    druid:
      url: jdbc:mysql://101.33.221.78:3306/blog_management_system?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true&useAffectedRows=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1900130214
  redis:
    host: xredis
    port: 6379
    password: wsadBABA168!
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 1972524359@qq.com
    password: dcbbklpqluffbfai
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  type-aliases-package: com.xx.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

jwt:
  tokenHeader: Authorization # jwt存储的请求头
  secret: admin-secret # jwt 加解密使用的密钥
  expiration: 86400 # jwt过期时间（60*60*24*7）
  #  expiration: 604800 # jwt过期时间（60*60*24*7）
  tokenHead: 'Bearer'  # jwt负载中拿到开头

stack:
  requestPath: /**
  local-path: /xx/fileUpload/
  #localPath: D:/fileUpload/